name: Push-to-EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@v2.1.5
      env:
        SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${ { secrets.HOST_DNS }}
        REMOTE_USER: ${ { secrets.USERNAME }}
        TARGET: ${ { secrets.TARGET_DIR }}
        SOURCE: "./"

